In [1]:
## import pandas 
import pandas as pd

In [2]:
## import data
taxi_df= pd.read_csv("311-data.csv")

In [3]:
taxi_df.head(20)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
0,67345192,12/31/2025 11:58:25 PM,01/02/2026 11:55:46 AM,TLC,Taxi and Limousine Commission,Lost Property,Bag/Wallet,Purse,Taxi,10011.0,...,NaN,NaN,"120 5 AVENUE, MANHATTAN (NEW YORK), NY, 10011",NaN,NaN,NaN,NaN,40.738077,-73.992123,POINT (-73.992122616114 40.738076887271)
1,67348740,12/31/2025 11:20:23 PM,01/02/2026 01:27:51 PM,TLC,Taxi and Limousine Commission,Lost Property,Bag/Wallet,Backpack,Taxi,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
2,67349981,12/31/2025 11:05:23 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Discourteous,Street,11435.0,...,NaN,NaN,"148-25 89 AVENUE, QUEENS (JAMAICA), NY, 11435",NaN,NaN,NaN,NaN,40.704243,-73.807266,POINT (-73.807265995267 40.704243098808)
3,67348745,12/31/2025 10:50:29 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
4,67348746,12/31/2025 10:42:43 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,11369.0,...,NaN,NaN,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",NaN,NaN,NaN,NaN,40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
5,67353556,12/31/2025 08:13:18 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Fare/Tip/Receipt,Street,11369.0,...,NaN,QUEENS,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",NaN,NaN,NaN,NaN,40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
6,67347653,12/31/2025 08:10:17 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10007.0,...,NaN,NaN,"22 DEY STREET, MANHATTAN (NEW YORK), NY, 10007",NaN,NaN,NaN,NaN,40.710835,-74.010381,POINT (-74.010381056064 40.710834971)
7,67351142,12/31/2025 08:03:06 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
8,67348747,12/31/2025 07:47:22 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Unsafe Driving - Passenger,Street,11369.0,...,NaN,NaN,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",NaN,NaN,NaN,NaN,40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
9,67346486,12/31/2025 07:22:44 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Non Passenger,Unauthorized Pick-Up Location,Street,10001.0,...,NaN,NaN,"455 8 AVENUE, MANHATTAN (NEW YORK), NY, 10001",NaN,NaN,NaN,NaN,40.751389,-73.994059,POINT (-73.994059200662 40.751389039705)
10,67350060,12/31/2025 07:02:49 PM,01/23/2026 09:19:26 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10475.0,...,NaN,BRONX,"BAY PLAZA, BRONX ,NY, 10475",NaN,NaN,NaN,NaN,40.868908,-73.825894,POINT (-73.825893678807 40.868907608336)
11,67348869,12/31/2025 06:43:52 PM,01/23/2026 09:18:23 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,11216.0,...,NaN,NaN,"1160 FULTON STREET, BROOKLYN, NY, 11216",NaN,NaN,NaN,NaN,40.680906,-73.954658,POINT (-73.954658243732 40.680905792303)
12,67351258,12/31/2025 06:23:30 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10036.0,...,NaN,NaN,"570 11 AVENUE, MANHATTAN (NEW YORK), NY, 10036",NaN,NaN,NaN,NaN,40.761397,-73.997885,POINT (-73.997884671036 40.761396514271)
13,67353557,12/31/2025 05:47:17 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Unsafe Driving,Street,10022.0,...,NaN,NaN,"EAST 54 STREET AND LEXINGTON AVENUE, MANHATT...",NaN,NaN,NaN,NaN,40.758999,-73.970534,POINT (-73.970534455264 40.758999348952)
14,67350063,12/31/2025 05:30:02 PM,01/23/2026 09:17:05 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10003.0,...,NaN,NaN,"21 EAST 8 STREET, MANHATTAN (NEW YORK), NY,...",NaN,NaN,NaN,NaN,40.731778,-73.995201,POINT (-73.995201131388 40.731777847362)
15,67353529,12/31/2025 05:03:59 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint - Credit Card,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
16,67348868,12/31/2025 04:36:53 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,11414.0,...,NaN,NaN,"53 BROADWAY, QUEENS (HOWARD BEACH), NY, 11414",NaN,NaN,NaN,NaN,40.657329,-73.829888,POINT (-73.829887844518 40.657329326174)
17,67347639,12/31/2025 04:35:12 PM,01/06/2026 09:17:02 AM,TLC,Taxi and Limousine Commission,Taxi Compliment,Driver Compliment,Above and Beyond to Help,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,67352321,12/31/2025 04:24:49 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,Denied Request,Street,10028.0,...,NaN,MANHATTAN,"203 EAST 86 STREET, MANHATTAN (NEW YORK), NY...",NaN,NaN,NaN,NaN,40.778698,-73.953675,POINT (-73.953674533077 40.778698294727)
19,67345180,12/31/2025 04:14:00 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Passenger,License Not Displayed,Street,10462.0,...,NaN,BRONX,"2111 STARLING AVENUE, BRONX, NY, 10462",NaN,NaN,NaN,NaN,40.836099,-73.854753,POINT (-73.854752896596 40.836098893609)

In [6]:
## sampling data

taxi_df.sample(10)

,Unique Key,Created Date,Closed Date,Agency,Agency Name,Problem (formerly Complaint Type),Problem Detail (formerly Descriptor),Additional Details,Location Type,Incident Zip,...,Vehicle Type,Taxi Company Borough,Taxi Pick Up Location,Bridge Highway Name,Bridge Highway Direction,Road Ramp,Bridge Highway Segment,Latitude,Longitude,Location
35139,63761725,01/14/2025 04:10:57 PM,04/15/2025 09:01:36 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10028.0,...,NaN,NaN,"1577 2 AVENUE, MANHATTAN (NEW YORK), NY, 10028",NaN,NaN,NaN,NaN,40.775149,-73.953742,POINT (-73.953741991331 40.775149376683)
32574,64048422,02/11/2025 06:53:59 AM,02/11/2025 11:58:42 AM,TLC,Taxi and Limousine Commission,Lost Property,Electronics/Phones,Cell Phone,Taxi,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
6030,66704822,11/02/2025 01:28:04 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Vehicle Complaint,Broken/Missing Equipment,Street,11430.0,...,NaN,NaN,"JOHN F KENNEDY AIRPORT, QUEENS (JAMAICA) ,NY, ...",NaN,NaN,NaN,NaN,40.648320,-73.788281,POINT (-73.788281251302 40.648320486201)
33861,63925393,01/29/2025 07:59:57 AM,04/15/2025 03:27:29 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10023.0,...,NaN,NaN,"1819 BROADWAY, MANHATTAN (NEW YORK), NY, 10023",NaN,NaN,NaN,NaN,40.768586,-73.982086,POINT (-73.982086355724 40.768586364308)
21613,65190766,06/07/2025 12:12:30 PM,10/23/2025 02:12:01 PM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10010.0,...,NaN,NaN,"8 WEST 23 STREET, MANHATTAN (NEW YORK), NY, ...",NaN,NaN,NaN,NaN,40.741804,-73.990206,POINT (-73.990205947825 40.741804112912)
2136,67100415,12/08/2025 09:45:19 PM,12/11/2025 03:29:58 PM,TLC,Taxi and Limousine Commission,Lost Property,Electronics/Phones,Cell Phone,Taxi,10001.0,...,NaN,NaN,"50 HUDSON YARDS, MANHATTAN (NEW YORK), NY, 10001",NaN,NaN,NaN,NaN,40.754249,-73.999390,POINT (-73.999390013247 40.754249217211)
10851,66264404,09/24/2025 04:57:05 PM,NaN,TLC,Taxi and Limousine Commission,Taxi Complaint,Driver Complaint - Passenger,Fare/Tip Complaint - Credit Card,Highway,11369.0,...,NaN,NaN,"LA GUARDIA AIRPORT, QUEENS (EAST ELMHURST) ,NY...",FDR Dr,Southbound/Downtown,Roadway,E 96 St (Exit 14) - E 71 St (Exit 13),40.774421,-73.877294,POINT (-73.877294105139 40.774420865988)
262,67323054,12/28/2025 03:08:55 PM,NaN,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,11218.0,...,NaN,NaN,"130 EAST 5 STREET, BROOKLYN, NY, 11218",NaN,NaN,NaN,NaN,40.649781,-73.976741,POINT (-73.976741478374 40.649781102088)
24810,64874753,05/07/2025 01:56:25 PM,05/08/2025 02:56:22 PM,TLC,Taxi and Limousine Commission,Lost Property,Jewelry,Ring,Taxi,10019.0,...,NaN,NaN,"2 WEST 57 STREET, MANHATTAN (NEW YORK), NY, ...",NaN,NaN,NaN,NaN,40.763164,-73.974460,POINT (-73.97446015393 40.763164061875)
25305,64823594,05/02/2025 09:00:03 PM,06/16/2025 08:52:12 AM,TLC,Taxi and Limousine Commission,For Hire Vehicle Complaint,Driver Complaint - Non Passenger,Unsafe Driving,Street,10003.0,...,NaN,NaN,"774 BROADWAY, MANHATTAN (NEW YORK), NY, 10003",NaN,NaN,NaN,NaN,40.731303,-73.991799,POINT (-73.991798683755 40.731302812719)

In [7]:
## gauging complaints
## that's annoying that fare/tip is different ; I'm also curious about contract dispute

taxi_df["Additional Details"].unique()

<StringArray>
[                           'Purse',                         'Backpack',
                     'Discourteous',               'Fare/Tip Complaint',
                 'Fare/Tip/Receipt',                   'Unsafe Driving',
       'Unsafe Driving - Passenger',    'Unauthorized Pick-Up Location',
 'Fare/Tip Complaint - Credit Card',         'Above and Beyond to Help',
                   'Denied Request',            'License Not Displayed',
                     'Shopping Bag',                            'Other',
                          'Earring',                         'Tote Bag',
   'Unsafe Driving - Non-Passenger',                          'Glasses',
                  'Route Complaint',                       'Cell Phone',
                  'Refused Pick-Up',           'Unclean Condition/Odor',
    'Refusal to Accept Credit Card',          'Unlicensed/Unauthorized',
                             'Keys',                         'Suitcase',
                              'Hat',                           'Wallet',
                           'Camera',                  'Computer/Laptop',
            'Service Delay/No Show',    'Returned Passenger's Property',
                        'Briefcase',                           'Gloves',
                   'Cell Phone Use',                           'Jacket',
   'Cell Phone Use - Non-Passenger',                            'Watch',
                         'Necklace',                             'Coat',
                 'Combined Pickups',         'Broken/Missing Equipment',
                           'Guitar',            'Courteous/Kind/Polite',
                            'Scarf',   'Unauthorized Vehicle Operation',
                         'Passport',                             'Ring',
                              'Toy',                            'Shoes',
                       'Money Clip',     'Broken Card Reader or Screen',
                   'Broken/Missing',                         'Stroller',
                 'Drop-Off Refused',                  'Binder/Notebook',
                         'Umbrella',            'Reward/Tip Submission',
   'Passenger Without Enough Funds',                          'Racquet',
                         'Envelope',                            'Pager',
           'Handheld Organizer/PDA',    'Discourteous/Harassment/Abuse',
                 'Contract Dispute',                          'Planner',
                  'MP3 Player/iPod',                         'Document',
                         'Bracelet',                             'Book',
                             'Ball',                              'Box',
                   'Religious Item',                                nan,
                                '1',                           'Folder',
                              'Bat',                        'Saxophone',
                         'Keyboard']
Length: 79, dtype: str

In [10]:
## ok... how many happened in queens and/or at an airport? 

taxi_df["Park Borough"].unique()

<StringArray>
['MANHATTAN', 'QUEENS', 'BRONX', 'BROOKLYN', 'Unspecified', 'STATEN ISLAND']
Length: 6, dtype: str

In [11]:
taxi_df["Park Borough"].value_counts()

Park Borough
MANHATTAN        20767
QUEENS            8232
BROOKLYN          5102
BRONX             1252
Unspecified        739
STATEN ISLAND      133
Name: count, dtype: int64

In [20]:
## counting citations at JFK

count = taxi_df['Taxi Pick Up Location'].str.contains('KENNEDY', na=False).sum()
print(f"KENNEDY count: {count}")

KENNEDY count: 3915

In [28]:
## counting mentions of LGA

la_guardia_count = taxi_df['Taxi Pick Up Location'].str.contains('LA GUARDIA', na=False).sum()
laguardia_count = taxi_df['Taxi Pick Up Location'].str.contains('LAGUARDIA', na=False).sum()
total = la_guardia_count + laguardia_count
print(f"LA GUARDIA: {la_guardia_count}")
print(f"LaGuardia: {laguardia_count}")
print(f"Total: {total}")

LA GUARDIA: 1737
LaGuardia: 14
Total: 1751